# Generated by Django 3.0.8 on 2022-04-02 16:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=70)),
                ('domain', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=20)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ('-date_updated',),
            },
        ),
        migrations.CreateModel(
            name='CustomMessages',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('to_email', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=70)),
                ('html_data', models.TextField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Clients')),
            ],
            options={
                'verbose_name': 'Custom Message',
                'verbose_name_plural': 'Custom Messages',
                'db_table': 'custom_messages',
                'ordering': ('-date_updated',),
            },
        ),
        migrations.CreateModel(
            name='ContactFormMessages',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Clients')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'db_table': 'contact_form_messages',
                'ordering': ('-date_updated',),
            },
        ),
    ]
