# Generated by Django 3.0.8 on 2022-08-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_message_smsclient_smstemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smstemplate',
            name='template_id',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='OSPERB', max_length=8),
            preserve_default=False,
        ),
    ]
