# Generated by Django 3.0.8 on 2022-08-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220831_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsclient',
            name='pending_payment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smsclient',
            name='total_sms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smsclient',
            name='unpaid_sms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
