# Generated by Django 3.0.8 on 2024-07-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220831_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsclient',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
