# Generated by Django 3.0.8 on 2024-07-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_smsclient_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.SmsTemplate'),
        ),
        migrations.AlterField(
            model_name='smsclient',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
