# Generated by Django 3.0.8 on 2022-08-31 10:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=70)),
                ('domain', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=20)),
                ('pending_payment', models.CharField(max_length=20)),
                ('total_sms', models.CharField(max_length=20)),
                ('unpayed_sms', models.CharField(max_length=20)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sms Client',
                'verbose_name_plural': 'sms_Clients',
                'db_table': 'sms_clients',
                'ordering': ('-date_updated',),
            },
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_id', models.CharField(max_length=128)),
                ('template_name', models.CharField(max_length=128)),
                ('template', models.TextField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sms template',
                'verbose_name_plural': 'sms_templates',
                'db_table': 'sms_templates',
                'ordering': ('-date_updated',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('sms_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Clients')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SmsClient')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'messages',
                'db_table': 'message',
                'ordering': ('-date_updated',),
            },
        ),
    ]
