# Generated by Django 3.0.8 on 2022-08-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220831_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplate',
            name='sms_charge',
            field=models.CharField(default=40, max_length=128),
        ),
    ]
