# Generated by Django 3.0.8 on 2022-08-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_smstemplate_sms_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsclient',
            old_name='unpayed_sms',
            new_name='unpaid_sms',
        ),
    ]
