# Generated by Django 3.0.8 on 2022-08-31 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220831_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sms_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SmsClient'),
        ),
        migrations.AlterField(
            model_name='message',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SmsTemplate'),
        ),
    ]
