# Generated by Django 3.0.8 on 2024-07-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_smsclient_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsclient',
            name='payment_type',
            field=models.CharField(choices=[('postpaid', 'postpaid'), ('prepaid', 'prepaid')], default='postpaid', max_length=9),
        ),
    ]
