# Generated by Django 3.0.8 on 2024-07-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20240711_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
