# Generated by Django 5.1.3 on 2026-05-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_message_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsclient',
            name='paid_sms_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smsclient',
            name='total_sms_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smsclient',
            name='unpaid_sms_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
